### ISSUE TITLE
Industrial API Mandate

### ISSUE THREAD

**Issue by zantiu** [cesmii/API#1]
First of all appreciate the initiative.

However we need to take one step back. The biggest issue we have in industry is that there are almost no open interfaces between applications.

My proposal is to make an Industrial API Manadate first, inspired by the Bezos API Mandate.

For reference the original mandate:

```
1. All teams will henceforth expose their data and functionality through API interfaces.

2. Teams must communicate with each other through these interfaces.

3. There will be no other form of interprocess communication allowed: no direct linking, no direct reads of another team’s data store, no shared-memory model, no back-doors whatsoever. The only communication allowed is via service interface calls over the network.

4. It doesn’t matter what technology they use. HTTP, Corba, Pubsub, custom protocols — doesn’t matter.

5. All service interfaces, without exception, must be designed from the ground up to be externalizable. That is to say, the team must plan and design to be able to expose the interface to developers in the outside world. No exceptions.

6. Anyone who doesn’t do this will be fired.

7. Thank you; have a nice day!
```

So for example:

```
1. All applications will henceforth expose their data and functionality through open interfaces.

2. Applications must communicate with each other through these interfaces.

3. There will be no other form of interapplication communication allowed: no direct linking, no direct reads of another applications's data store, no shared-memory model, no back-doors whatsoever. The only communication allowed is via API interface calls over the network.

4. It doesn’t matter what technology they use. HTTP, Corba, Pubsub, custom protocols — doesn’t matter.

5. All API interfaces, without exception, must be designed from the ground up to be externalizable. That is to say, the team must plan and design to be able to expose the interface to developers in the outside world. No exceptions.

6. Anyone who doesn’t do this will be fired.

7. Thank you; have a nice day!```

**Comment by jwise-mfg** [comment]
While stories of that actual memo are [probably apocryphal](https://gist.github.com/chitchcock/1281611), the spirit of the requirement was certainly influential, and I agree with its applicability here.

Unfortunately, neither myself, nor CESMII, nor the Working Group, have the same authority over implementers as Bezos did over his teams, so we cannot implement this. 

We do need manufacturers to demand this, though. [CESMII's Executive Council](https://www.cesmii.org/about/sm-executive-council/) is working on creating these kinds of mandates, using the combined voices of some of the industry's biggest and most influential companies. So while I'm closing the issue as outside of the scope of the API itself, please know there are many folks who share your conviction and are working on it!
