### ISSUE TITLE
Feedback on API [HighByte]

### ISSUE THREAD

**Issue by aronsemle** [cesmii/API#3]
Some feedback below.

```
Implementations MAY support a HTML serialization for all responses, that proposes an embed-able UI for the response data (for example, HTMX). Such pre-rendered responses MAY include Hyperlinks to follow-up queries in the same format, facilitating progressive UI expansion.
```
This one seems odd to me, and may need more examples of end use cases? Binary and JSON I get.

- 3.2.1 LiveValue

1. This is a nit pick, but 'Live' to me implies not cached/stale. I might change this to 'Latest'?
2. I'd love to remove the concept of 'quality' and just return data if we can vs. no data if it's bad with some way to get an error message back through the API on a failure. Quality to me is an OT legacy thing that isn't that useful outside of OT
3. The interpolation metadata seems odd? Remove it for LiveValue?
4. I would make UPDATE/POST (i.e. writes) a different endpoint. As a dev, this gives me more options to secure it, optimize it, etc
5. If I read many elements and one fails, (ex. bad ID) what is the behavior? 

- General feedback

1. I think it would be good to put some requirements around ElementID. It's a string type, human readable, etc? I'm just thinking of OPC UA where nodeids can be different data type, and it's a mess
2. I would make the data/metadata queries different endpoints as well. It's not often that you want to mix the fast changing data with the stale metadata, in my experience
3. There is nothing in here around subscriptions? It would be nice to have an interface that says "subscribe to elementID X" and get streamed data changes
4. These interfaces should define failure causes, what is returned on a read failure, bad elementID, etc
6. I think most of these could use one or two example use cases to help frame them for the reader? Maybe that's a different doc?

`"Implementations MUST NOT support un-encrypted HTTP in production"`

I'd remove this or not make it a MUST. I think we must support encryption, but it's 100% on the customer and their setup to enable that, so I don't see how this can be part of a spec?

**Comment by randy-armstrong** [comment]
1) The StatusCode in OPC UA is not the same as COM DA Quality. It is an error code indicating the reason for the Bad data. I think Quality should just be called 'Status' or 'StatusCode'

2) Returning metadata with a value is a convenience that comes with significant cost. Clients that know what they asked for do not need it so there should be an option available to only return values. 

3) Different Endpoints for different services implies the need for a discovery service (i.e. GetEndpoints from OPC UA).

4) If each LiveValue has a StatusCode then that would handle the issues related to partial success.

5) If this is to be a generic API to some unknown system there cannot be requirements on the identifiers. They need to be opaque strings chosen based on the needs of the system being accessed. All OPC UA NodeIds in JSON are strings now so the different IdTypes are not something a Client cares about.

6) Subscribing to a LiveValue is a complex problem when accessing a system where the underlying data is not already being monitored. Questions like sampling rates, deadbands, queue lengths need to be addressed, Also the technology available for 'streaming' varies widely. MQTT has intrinsic QoS capabilities that can handle network interruptions. Others like WebSockets or long polling with HTTPS need  and API that can manage the QoS features. 

7) Allow unencrypted HTTPS opens up many attack vectors that would have to explored and documented. Mandating HTTPS greatly reduces the effort needed to complete this API.

**Comment by jwise-mfg** [comment]
Closing, since this has been split into issues for each individual topic.
