### ISSUE TITLE
HTML as a Response Serialisation Format

### ISSUE THREAD

**Issue by germanandy** [cesmii/API#4]
In section 3.1.1 Response Serialization:

"Implementations MAY support a HTML serialization for all responses, that proposes an embed-able UI for the response data (for example, HTMX). Such pre-rendered responses MAY include Hyperlinks to follow-up queries in the same format, facilitating progressive UI expansion"

I believe that including HTML in this context could lead to confusion and implementation issues
 
HTML is not a serialisation format.  Including HTML here conflates data serialisation with content presentation, these are not the same thing.

This could lead to:
-  confusion among developers
-  encourages bloat
- mixing of concerns (data retrieval and UI rendering) reduces clarity
- security risks introduced if clients consume the HTML as-is
- HTML responses would be larger and would be hard to extract data from
- extracting data from the HTML would be less performant and error prone

Recommendation:
- Clarify whether the API is intended for data exchange between systems only or if it is also intended for delivering UI components.
- Limit response serialisation formats to those meant for machine readable data interchange, such as JSON, XML, Protocol Buffers, etc.
- If UI/HTML is a core concern for the API, manage this separately

**Comment by jwise-mfg** [comment]
The Working Group met today and agreed with this feedback, HTML serialization has been removed from the RFC in the working draft.
Resolving as fixed.
